# Generated by Django 3.0.7 on 2025-08-30 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_app', '0016_auto_20250831_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='workshoptype',
            name='certification_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshoptype',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='workshoptype',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshoptype',
            name='materials_provided',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshoptype',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='WorkshopSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration', models.IntegerField(default=15, help_text='Break duration in minutes')),
                ('max_participants', models.PositiveIntegerField(default=30)),
                ('venue_details', models.TextField(blank=True)),
                ('equipment_required', models.TextField(blank=True)),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='workshop_app.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('workshop_created', 'Workshop Created'), ('workshop_accepted', 'Workshop Accepted'), ('workshop_rejected', 'Workshop Rejected'), ('workshop_reminder', 'Workshop Reminder'), ('new_comment', 'New Comment'), ('rating_received', 'Rating Received')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop_app.Workshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='workshop_app.Workshop')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.AddField(
            model_name='workshoptype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_app.WorkshopCategory'),
        ),
        migrations.CreateModel(
            name='WorkshopRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1-5')),
                ('feedback', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='workshop_app.Workshop')),
            ],
            options={
                'unique_together': {('workshop', 'user')},
            },
        ),
    ]
